# Generated by Django 3.2.6 on 2021-08-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(default=0.0)),
                ('Hardness', models.FloatField(default=0.0)),
                ('Solids', models.FloatField(default=0.0)),
                ('Chloramines', models.FloatField(default=0.0)),
                ('Sulfate', models.FloatField(default=0.0)),
                ('Conductivity', models.FloatField(default=0.0)),
                ('Organic_carbon', models.FloatField(default=0.0)),
                ('Trihalomethanes', models.FloatField(default=0.0)),
                ('Turbidity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Potability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0.0)),
                ('input_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterpotability.independentvariables')),
            ],
        ),
    ]
