# Generated by Django 3.2.6 on 2021-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpotability', '0002_entervariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(default=0.0)),
                ('Hardness', models.FloatField(default=0.0)),
                ('Solids', models.FloatField(default=0.0)),
                ('Chloramines', models.FloatField(default=0.0)),
                ('Sulfate', models.FloatField(default=0.0)),
                ('Conductivity', models.FloatField(default=0.0)),
                ('Organic_carbon', models.FloatField(default=0.0)),
                ('Trihalomethanes', models.FloatField(default=0.0)),
                ('Turbidity', models.FloatField(default=0.0)),
                ('Potability', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='EnterVariables',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='potability',
            name='input_var',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='IndependentVariables',
        ),
        migrations.DeleteModel(
            name='Potability',
        ),
    ]
