# Generated by Django 3.2.6 on 2021-08-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpotability', '0003_auto_20210816_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='Potability',
            field=models.CharField(max_length=20),
        ),
    ]
